=== sak9309/CIA-2047251-/CIA.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Employee_Management_System">
		<xsd:complexType>
		
		<xsd:element name="Members">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="ID" type="xsd:string"/>
					<xsd:element name="Name" type="xsd:string"/>
					<xsd:element name="Age" type="xsd:integer"/>
					<xsd:element name="Salary" type="xsd: mySalary>
					<xsd:element name="Email" type="xsd:string"/>
					<xsd:element name="MobNum" type="xsd:integer"/>
					<xsd:element name="Designation" type="xsd:string"/>
					
					
				</xsd:sequence>	
			</xsd:complexType>
		</xsd:element>

	</xsd:complexType>
	</xsd:element>
<xsd:simpleType name="mySalary">
  <xsd:restriction base="xs:integer">
    <xsd:minInclusive value="50,000"/>
    <xsd:maxInclusive value="2,00,000"/>
  </xsd:restriction>
</xsd:simpleType>
</xsd:schema>

=== sak9309/CIA-2047251-/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CIA.xsl"?>
<Employee_Management_System xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="CIA.xsd">
	
	<Members>
		<ID>1A</ID>
	    <Name>Ms. Pranati Panday</Name>
		<Age>38</Age>
		<Salary>52000</Salary>
		<Email>panday.p@gmail.com</Email>
		<MobNum>9324509867</MobNum>
		<Designation>Associate Project Manager</Designation>
	</Members>
	
	<Members>
		<ID>2B</ID>
	    <Name>Mr. Prakash Jha</Name>
		<Age>50</Age>
		<Salary>58000</Salary>
		<Email>jha.prakash@gmail.com</Email>
		<MobNum>9456709877</MobNum>
		<Designation>Project Manager</Designation>
	</Members>
	
	<Members>
		<ID>3C</ID>
	    <Name>Mrs. Shuchi Bharti</Name>
		<Age>46</Age>
		<Salary>62000</Salary>
		<Email>bharti89@gmail.com</Email>
		<MobNum>8900941034</MobNum>
		<Designation>Team Leader</Designation>
	</Members>
	
	<Members>
		<ID>4D</ID>
	    <Name>Mr. Raghav Tripathi</Name>
		<Age>38</Age>
		<Salary>52000</Salary>
		<Email>triraghav@gmail.com</Email>
		<MobNum>7867800910</MobNum>
		<Designation>Assistant Developer</Designation>
	</Members>
	
	<Members>
		<ID>5E</ID>
	    <Name>Mrs. Asha Rastogi</Name>
		<Age>58</Age>
		<Salary>64,000</Salary>
		<Email>asha101@gmail.com</Email>
		<MobNum>9320000867</MobNum>
		<Designation>Associate Project Manager</Designation>
	</Members>
	
	
</Employee_Management_System >
